### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  drone1: 10.42.0.119
  drone2: 10.42.0.62
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
  - topic_name: /drone1/optitrack/pose # send the messages of this ROS topic
    msg_type: geometry_msgs/PoseStamped 
    max_freq: 100
    srcIP: self
    srcPort: 3001
  - topic_name: /drone2/optitrack/pose
    msg_type: geometry_msgs/PoseStamped 
    max_freq: 100 
    srcIP: self 
    srcPort: 3002 
  - topic_name: /drone3/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 200
    srcIP: self
    srcPort: 3300
  - topic_name: /traj_start_trigger
    msg_type: geometry_msgs/PoseStamped
    max_freq: 1
    srcIP: self
    srcPort: 3001
  - topic_name: /pedestrian1/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3011
  - topic_name: /pedestrian2/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3012
  - topic_name: /pedestrian3/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3013
  - topic_name: /px4ctrl/takeoff_land
    msg_type: quadrotor_msgs/TakeoffLand
    max_freq: 10
    srcIP: self
    srcPort: 3002

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /shared_trajectory # the received messages will be published in this topic
    msg_type: std_msgs/String # ROS message type (rosmsg style)
    srcIP: drone1 # message source IPname
    srcPort: 3005 # message source port

  - topic_name: chatter_recv_2 # the received messages will be published in this topic
    msg_type: std_msgs/String # ROS message type (rosmsg style)
    srcIP: drone2 # message source IPname
    srcPort: 3004 # message source port


